step1 and step2
RidTiff/react-burger pull request #1
Opened 2022-09-17 21:42 UTC by RidTiff

2022-09-17 23:42 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец! Приложение уже начинает обрастать функционалом.** 🔥

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Стоит переименовать корневой файл index.tsx в index.js. Т.к вы пока не используете typescript. В будущем вы вернетесь к этому.

- Лучше удалить файл obnull.module.css. Вместо этого стоит в глобальном файле написать вот такие стили: 
```css
  * {
    margin: 0;
    padding: 0;
  }
```

- Исправить путаницу с пропсами в компоненте `modal`

- Оптимизировать вывод ингридиентов в компонентах: 'BurgerIngredients' и 'BurgerConstructor'.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами, это затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/App/App.js
> +    getIngredients();
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-09-17 23:42 UTC, ArslanMustafin commented on src/utils/api.js
> +};
**Можно лучше:** Функцию лучше назвать `checkResponse`

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/App/App.js
> +      )}
**Надо исправить:** Лучше манипулировать модальными окнами их стейтом, в нужном компоненте, в данном случае это `BurgerConstructor`. Иначе при каждом изменении стейта, всё приложение будет заново рендериться.

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/App/App.js
> +      )}
**Надо исправить:** Описал ниже как можно оптимизировать логику. В этом случае нужный компонент это `BurgerIngredients`

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/App/App.js
> +  };
**Надо исправить:** Обработчики событий тоже стоит перенести в соответствующие файлы.
Первые 2 - BurgerIngredients
Остальные в BurgerConstructor.

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/PointHeader/PointHeader.js
> +        </div>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой. Вообщем нужно чтобы ссылки были ссылками, а не другими семантическими элементами.

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +              ))}
**Можно лучше:** Здесь и далее.

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/BurgerIngredients/BurgerIngredients.js
> +          </Tab>
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +          ))}
**Надо исправить:** Не стоит делать фильтрацию в выводе jsx. лучше сделать её заранее. Вот так например:
```js 
  const bun = useMemo(() => ingredients.find((ingredient) => ingredient.type === "bun"), [ingredients]);
```
Нам незачем использовать 2 переменные, т.к булка у нас всегда будет одна.

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +          ))}
**Надо исправить:** Описал выше аналогичную проблему.

2022-09-17 23:42 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +        <Button type='primary' size='medium' onClick={() => onRequestOpen()}>
**Можно лучше:** Тут можно не создавать анонимную функцию, т.к мы не используем какие-либо параметры в функции `onRequestOpen`. Т.е можно просто написать вот так:
```js 
<Button type='primary' size='medium' onClick={onRequestOpen}>
```

2022-09-17 23:42 UTC, ArslanDev666 commented on src/components/App/App.js
> +        });
**Можно лучше**
Хорошо, что обрабатывается ошибка запроса к api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит. 

Также отличным улучшением будет показ лоадера, во время загрузки данных. Вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-09-17 23:42 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +              ))}
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-09-17 23:42 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientDetails.js
> +      <img className='pb-4 pt-10' src={item.image_large} />
**Можно лучше:** Для элемента img следует указывать атрибут alt. Этот атрибут дает понять пользователям, что изображено на этой картинке.

2022-09-17 23:42 UTC, ArslanDev666 commented on src/components/Main/Main.js
> +}
**Надо исправить:** Для этого компонента, также следует прописать `propTypes`

2022-09-17 23:42 UTC, ArslanDev666 commented on src/components/Modal/Modal.js
> +export default function Modal({ children, onRequestClose, title }) {
**Можно лучше:** Лучше переименовать пропс `onRequestClose` в `onClose`. Так легче читается, и смысл остаётся такой же.

2022-09-18 20:28 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Ревью отклонено, по причине того, что приложение не билдиться и не запускается. А также прошлые замечания не были исправлены.

2022-09-24 18:29 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Не все замечания с 1 ревью были исправлены.
Напоминаю, что работа не будет принята, пока все замечания - `Надо исправить` не будут исправлены.

2022-09-24 18:29 UTC, ArslanDev666 commented on src/components/Modal/Modal.js
> +};
**Надо исправить:** PropTypes не соответствует передаваемым пропсам.

2022-09-24 18:29 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +                <div className={`${styles.card} mr-6 mb-6`} key={item._id} onClick={() => handleIngredientClick(item)}>
**Можно лучше**
используйте useMemo, что бы фильтрация ингредиентов не вызывалась при каждом ренедере, например:
```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
.....
```

2022-09-24 18:29 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +          <div className={`${styles.ingredient} mt-6`}>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-09-24 18:29 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +export default function BurgerConstructor(ingredients) {
**Можно лучше:** Не забывайте, что к пропсам, тоже можно применять деструктуризацию.

2022-09-26 11:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Не все замечания с 1 ревью были исправлены.

## Надо исправить:

- Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

  Например

  ```
  <a href="#" class="......">
    <BurgerIcon type="primary" /> Конструктор
  </a>
  ```

  В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой. Вообщем нужно чтобы ссылки были ссылками, а не другими семантическими элементами.

- Файл BurgerConstructor, там 2 похожие проблемы.
  Не стоит делать фильтрацию в выводе jsx. лучше сделать её заранее. Вот так например:

  ```js
  const bun = useMemo(() => ingredients.find((ingredient) => ingredient.type === "bun"), [ingredients]);
  ```

  Нам незачем использовать 2 переменные, т.к булка у нас всегда будет одна.


**_Более подробно эти и более мелкие мелкие замечания, также отмечены в коде._**

Напоминаю, что работа не будет принята, пока все замечания - `Надо исправить` не будут исправлены.

Если у вас возникнут, какие-либо вопросы, с радостью на них отвечу.

2022-09-26 11:58 UTC, RidTiff commented
> ## Code Review
> 
> Здравствуйте!
> 
> Не все замечания с 1 ревью были исправлены.
> ## Надо исправить:
> 
>     * Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`
>       Например
>       ```
>       <a href="#" class="......">
>         <BurgerIcon type="primary" /> Конструктор
>       </a>
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой. Вообщем нужно чтобы ссылки были ссылками, а не другими семантическими элементами.
> 
>     * Файл BurgerConstructor, там 2 похожие проблемы.
>       Не стоит делать фильтрацию в выводе jsx. лучше сделать её заранее. Вот так например:
>       ```js
>       const bun = useMemo(() => ingredients.find((ingredient) => ingredient.type === "bun"), [ingredients]);
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       Нам незачем использовать 2 переменные, т.к булка у нас всегда будет одна.
> 
> 
> **_Более подробно эти и более мелкие мелкие замечания, также отмечены в коде._**
> 
> Напоминаю, что работа не будет принята, пока все замечания - `Надо исправить` не будут исправлены.
> 
> Если у вас возникнут, какие-либо вопросы, с радостью на них отвечу.

2022-09-28 14:01 UTC, RidTiff commented
Пока что не проверяйте, добавляю правки

2022-09-28 14:14 UTC, RidTiff commented
Всё, можно проверять! Сильно извиняюсь за игнорируемые замечания из первого ревью. Честно - я не специально, я умудрился пролистать раскрытие ветки с еще 6 замечаниями...

2022-09-28 14:43 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  if (data.length != 0) {
**Можно лучше:** Лучше всегда использовать строгое сравнение `===` и строгое неравентсво `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

2022-09-28 14:55 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  );
**Можно лучше:**
Лучше написать вот так, тогда нам не придётся инициализировать новую переменную, а также делать фильтр в самом jsx. 
```js
export default function BurgerConstructor({ingredients: constructorIngredients}) {

//...

const { bun, ingredients } = useMemo(() => {
   return {
     bun: constructorIngredients.find((ingredient) => {
        return ingredient.type === 'bun';
    }),
    ingredients: constructorIngredients.filter((ingredient) => {
        return ingredient.type !== 'bun';
    })
  };
}, [constructorIngredients])

//...

}
```

2022-09-28 14:57 UTC, ArslanMustafin approved these changes
## Code review

### Вы молодец🔥, продолжайте стараться, и у вас обязательно всё получиться. Задание принимаю.

2022-09-29 15:25 UTC, merged